_wandb:
    value:
        cli_version: 0.19.10
        m: []
        python_version: 3.12.3
        t:
            "1":
                - 1
                - 2
                - 3
                - 5
                - 53
                - 55
            "2":
                - 1
                - 2
                - 3
                - 5
                - 53
                - 55
            "3":
                - 13
                - 16
                - 23
                - 55
            "4": 3.12.3
            "5": 0.19.10
            "8":
                - 3
                - 5
            "12": 0.19.10
            "13": windows-amd64
algorithm:
    value: PPO
data_path:
    value: sample.csv
timesteps:
    value: 10000
